name: 'Git Sync'

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  git-sync:
    if: github.repository == 'flamego/flamego.cn'
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "flamego/flamego.cn"
          source_branch: "main"
          destination_repo: ${{ secrets.SYNC_DESTINATION_REPO }}
          destination_branch: "main"
          destination_ssh_private_key: ${{ secrets.SYNC_DESTINATION_SSH_PRIVATE_KEY }}
